# Generated by Django 4.2 on 2023-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherinformation_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinformation',
            name='teacher',
            field=models.BooleanField(),
        ),
    ]
