# Generated by Django 4.2 on 2023-05-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacherinformation_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinformation',
            name='status',
            field=models.CharField(choices=[('a', 'approved'), ('u', 'under consideration'), ('d', 'deleted')], default='u', max_length=1),
        ),
    ]
