# Generated by Django 4.2 on 2023-05-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacherinformation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinformation',
            name='teacher',
        ),
    ]
