# Generated by Django 4.2 on 2023-05-08 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=350)),
                ('to', models.ManyToManyField(related_name='mass_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
