# Generated by Django 4.2 on 2023-05-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mass_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mass_Email',
            new_name='MassEmail',
        ),
    ]
