# Generated by Django 4.2 on 2023-05-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_massemails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massemails',
            old_name='body',
            new_name='current_body',
        ),
        migrations.RemoveField(
            model_name='massemails',
            name='to',
        ),
    ]
